YASN/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin

admin.autodiscover()

from posts.views import PostListView, UserProfileDetailView, \
    UserProfileEditView, PostCreateView, PostDetailView, PostEditView, \
    PostDeleteView, VoteFormView, PostListAllView


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', PostListView.as_view(), name='home'),
    url(r'^zakopalisko/$', PostListAllView.as_view(), name='lounge'),
    url(r'^login/$', "django.contrib.auth.views.login",
        {"template_name": "registration/login.html"}, name="login"),
    url(r'^logout/$',
        "django.contrib.auth.views.logout_then_login", name="logout"),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^users/(?P<slug>\w+)/$',
        UserProfileDetailView.as_view(), name='profile'),
    url(r'^edit_profile/$',
        login_required(UserProfileEditView.as_view()), name='edit_profile'),
    url(r'^post/create/$',
        login_required(PostCreateView.as_view()), name='create_post'),
    url(r'^post/(?P<pk>\d+)$',
        PostDetailView.as_view(), name='post_detail'),
    url(r'^post/edit/(?P<pk>\d+)$',
        login_required(PostEditView.as_view()), name='post_edit'),
    url(r'^post/delete/(?P<pk>\d+)$',
        login_required(PostDeleteView.as_view()), name='post_delete'),
    url(r'^vote/$', login_required(VoteFormView.as_view()), name="vote"),
)

posts/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse


class PostVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(PostVoteCountManager, self).get_queryset().annotate(
            votes=Count('vote')).order_by('-points', '-votes')


class Tag(models.Model):
    """ A specific Tag model in the webiste."""
    slug = models.SlugField(max_length=100, unique=True, blank=False)

    def __unicode__(self):
        return self.slug

    class Meta(object):
        verbose_name = "Tag"


class Post(models.Model):
    """A specific Post model in the webiste."""
    title = models.CharField('Title', max_length=100, blank=False)
    author = models.ForeignKey(User, blank=False)
    url = models.URLField('URL', max_length=100, blank=False)
    submitted_on = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    descriptions = models.TextField('Descriptions', max_length=100)
    points = models.DecimalField(default=0, max_digits=7, decimal_places=2)
    # points = models.FloatField(default=0.0)
    with_votes = PostVoteCountManager()
    objects = models.Manager()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": str(self.id)})


class Vote(models.Model):
    """ A specific Vote model in the website. """
    voter = models.ForeignKey(User, blank=False)
    post = models.ForeignKey(Post, blank=False)

    def __unicode__(self):
        return "%s voted on %s" % (self.voter.username, self.post.title)


class UserProfile(models.Model):
    """ A specific User Profile model. """
    user = models.OneToOneField(User, unique=True)
    about = models.TextField(null=True)
    website = models.URLField("My website", blank=True, max_length=150)

    def __unicode__(self):
        return "Profil %s" % self.user


def create_profile(**kw):
    user = kw["instance"]
    if kw["created"]:
        up = UserProfile(user=user)
        up.save()


post_save.connect(create_profile, sender=User)

posts/forms.py
# coding=utf-8
from django.forms import ModelForm
from models import UserProfile, Post, Vote


class UserProfileForm(ModelForm):
    class Meta(object):
        model = UserProfile
        exclude = ("user", )


class PostForm(ModelForm):
    class Meta(object):
        #todo widget for tags
        model = Post
        exclude = ("points", "author", "tags", )


class VoteForm(ModelForm):
    class Meta(object):
        model = Vote

posts/views.py
# coding=utf-8
import json
from django.db.models import Count

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, \
    DeleteView, FormView
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse, reverse_lazy

from .models import Post, UserProfile, Vote
from .forms import UserProfileForm, PostForm, VoteForm

number_votes_to_main = 1


class PostListView(ListView):
    model = Post
    queryset = Post.with_votes.annotate(count=Count('vote')).exclude(
        count__lt=number_votes_to_main)
    paginate_by = 5
    template_name = "posts/post_list.html"

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(post_id__in=links_in_page)
            voted = voted.values_list('post_id', flat=True)
            context["voted"] = voted
        return context


class PostListAllView(ListView):
    model = Post
    # queryset = Post.with_votes.all()
    queryset = Post.with_votes.annotate(count=Count('vote')).exclude(
        count__gte=number_votes_to_main)

    paginate_by = 5
    template_name = "posts/post_list_all.html"

    def get_context_data(self, **kwargs):
        context = super(PostListAllView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            posts_in_page = [post.id for post in context["object_list"]]
            voted = voted.filter(post_id__in=posts_in_page)
            voted = voted.values_list('post_id', flat=True)
            context["voted"] = voted
        return context


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/create_post.html"

    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.points = 0
        f.save()
        return super(PostCreateView, self).form_valid(form)


class PostDetailView(DetailView):
    model = Post


class PostEditView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/create_post.html"


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("home")


class UserProfileDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "posts/user_detail.html"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user


class UserProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "posts/edit_profile.html"

    # bierzemy tylko obiekt naszego zalogowanego człowieka
    def get_object(self, query=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("profile", kwargs={"slug": self.request.user})


class JSONForm(object):
    @staticmethod
    def create_response(vdict=None, valid_form=True):
        if not vdict:
            vdict = dict()
        response = HttpResponse(
            json.dumps(vdict),
            content_type='application/json'
        )
        response.status = 200 if valid_form else 500
        return response


class VoteFormBaseView(FormView):
    form_class = VoteForm

    @staticmethod
    def create_response(vdict=None, valid_form=True):
        if not vdict:
            vdict = dict()
        response = HttpResponse(
            json.dumps(vdict),
            content_type='application/json'
        )
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=form.data["post"])
        user = self.request.user
        prev_vote = Vote.objects.filter(voter=user, post=post)
        has_voted = (prev_vote.count() > 0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, post=post)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_vote[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors}
        return self.create_response(ret, False)


class VoteFormView(VoteFormBaseView, JSONForm):
    pass

templates/posts/create_post.html
{% extends "base.html" %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>

    <script>
        $("li.active").removeClass("active");
        $("li:eq(2)").addClass("active");
    </script>
{% endblock %}

templates/posts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Edit">
    </form>
{% endblock %}

templates/posts/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <p>Are you sure you want to delete: "{{ object.title }}"?</p>
    <form method="post" action="{% url 'post_delete' pk=object.pk %}">
    {% csrf_token %}
    <a href="{% url 'post_detail' pk=object.pk %}">Go back</a>
    <p><input type="submit" value="Confirm deletion"/></p>
    </form>
{% endblock %}

templates/posts/post_detail.html
{% extends "base.html" %}

{% block content %}
    {% if object.author == user %}
        <p><a href="{%  url 'post_edit' pk=object.pk %}">Edytuj</a>
        <a href="{% url 'post_delete' pk=object.pk %}">Usuń</a></p>
    {% endif %}
    <h2>Autor: <a href="{% url "profile" slug=object.author %}">{{ object.author }}</a></h2>
    <p><label>Link:</label> <a href="{{ object.url }}">{{ object.url }}</a></p>
    <p><label>Opis:</label> {{ object.descriptions }}</p>
    {% if object.tags.count %}
        <p><label>Tagi:</label>
            {{ object.tags.all|join:", " }}.
        </p>
    {% endif %}
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_developer = 1;
        var disqus_shortname = 'djangoexamplesocialnewswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}
    <dl>
    {% for post in object_list %}
        <form method="post" action="{% url 'vote' %}" class="vote_form">
            <dt>
            [ <span id="vote_count">{{ post.votes }}</span> ]
                {% csrf_token %}
                <input type="hidden" id="id_post" name="post" class="hidden_id" value="{{ post.pk }}" />
                <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
                {% if user.is_authenticated %}
                    {% if post.pk in voted %}
                        <button class="glyphicon glyphicon glyphicon-thumbs-up deeppink"><span></span></button>
                    {% else %}
                        <button class="glyphicon glyphicon glyphicon-thumbs-up"><span></span></button>
                    {% endif %}
                {% endif %}
            <b><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></b>
                <a class="seagreen" href="{{ post.url }}" target="_blank">[URL]</a>
            </dt>
            <dd>{{ post.descriptions }}</dd>
        </form>
        {% endfor %}

    </dl>

    {% if is_paginated %}
        <ul class="pager">
        {% if page_obj.has_previous %}
          <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a></li>
        {% else %}
          <li class="previous disabled"><a href="#">&larr; Newer</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="next"><a href="?page={{ page_obj.next_page_number }}">Older &rarr;</a></li>
        {% else %}
            <li class="next disabled"><a href="#">Older &rarr;</a></li>
        {% endif %}
        </ul>
    {% endif %}
    <script>
    document.onkeydown = function(event) {
        event = event || window.event;
        switch (event.keyCode || event.which) {
            case 37:
                alert('left');
                break;
            case 39:
                alert('right');
                break;
        }
    };
    </script>
{% endblock %}

templates/posts/post_list_all.html
{% extends 'base.html' %}
{% block content %}
    <dl>
    {% for post in object_list %}
        <form method="post" action="{% url 'vote' %}" class="vote_form">
            <dt> [ {{ post.votes }} ]
                {% csrf_token %}
                <input type="hidden" id="id_post" name="post" class="hidden_id" value="{{ post.pk }}" />
                <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
                {% if user.is_authenticated %}
                    {% if post.pk in voted %}
                        <button><span class="glyphicon glyphicon glyphicon-thumbs-up deeppink"></span></button>
                    {% else %}
                        <button><span class="glyphicon glyphicon glyphicon-thumbs-up"></span></button>
                    {% endif %}
                {% endif %}
            <b><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></b>
                <a class="seagreen" href="{{ post.url }}" target="_blank">[URL]</a>
            </dt>
            <dd>{{ post.descriptions }}</dd>
        </form>
        {% endfor %}

    </dl>

    {% if is_paginated %}
        <ul class="pager">
        {% if page_obj.has_previous %}
          <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a></li>
        {% else %}
          <li class="previous disabled"><a href="#">&larr; Newer</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="next"><a href="?page={{ page_obj.next_page_number }}">Older &rarr;</a></li>
        {% else %}
            <li class="next disabled"><a href="#">Older &rarr;</a></li>
        {% endif %}
        </ul>
    {% endif %}
    <script>
    document.onkeydown = function(event) {
        event = event || window.event;
        switch (event.keyCode || event.which) {
            case 37:
                $("button.next").click();
                break;
            case 39:
                $("next.a").click();

                break;
        }
    };
    $("li.active").removeClass("active");
    $("li:eq(1)").addClass("active");
    </script>
{% endblock %}

templates/posts/user_detail.html
{% extends "base.html" %}
{% block content %}
<h2>Profil użytkownika {{ object.username }}</h2>
    {% if object.userprofile.about %}
        <p><b>O sobie:</b> {{ object.userprofile.about }}</p>
    {% endif %}
    {% if object.userprofile.website %}
        <p><b>Strona domowa:</b> <a href="{{ object.userprofile.website }}">{{ object.userprofile.website }}</a></p>
    {% endif %}

    {% if object.username == user.username %}
        <p><a href="{% url 'edit_profile' %}">Edit my profile</a></p>
    {% endif %}


    <script>
        $("li.active").removeClass("active");
        $("li:eq(3)").addClass("active");
    </script>
{% endblock %}